export const FETCH_USER_REQUEST='FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS='FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR='FETCH_USER_ERROR';

export const DELETE_USER='DELETE_USER';
export const ADD_USER='ADD_USER';
export const EDIT_USER='EDIT_USER';