export const SAVE_USER_TO_SERVER_REQUEST = 'SAVE_USER_TO_SERVER_REQUEST'
export const SAVE_USER_TO_SERVER_SUCCESS = 'SAVE_USER_TO_SERVER_SUCCESS'
export const SAVE_USER_TO_SERVER_FALIURE = 'SAVE_USER_TO_SERVER_FALIURE'
